version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: phonebook-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phonebook
      MYSQL_USER: phonebook_user
      MYSQL_PASSWORD: phonebook_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data: